# Generated by Django 5.2.7 on 2025-10-27 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('image_in', models.ImageField(blank=True, null=True, upload_to='checkinimages/')),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('image_out', models.ImageField(blank=True, null=True, upload_to='checkoutimages/')),
                ('status', models.CharField(blank=True, choices=[('Present', 'Present'), ('Early Leave', 'Early Leave'), ('Absent', 'Absent'), ('Half Day', 'Half Day'), ('On Leave', 'On Leave'), ('Holiday', 'Holiday')], max_length=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
            options={
                'ordering': ('-checkin_time',),
            },
        ),
    ]
