# Generated by Django 5.2.7 on 2025-10-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='image_in',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='image_out',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='checkin_image',
            field=models.ImageField(blank=True, null=True, upload_to='checkin_images/'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='checkout_image',
            field=models.ImageField(blank=True, null=True, upload_to='checkout_images/'),
        ),
    ]
