# Generated by Django 5.2.7 on 2025-10-27 09:14

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendancerecord_image_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='checkin_image',
            field=models.ImageField(blank=True, null=True, upload_to=attendance.models.employee_checkin_path),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='checkout_image',
            field=models.ImageField(blank=True, null=True, upload_to=attendance.models.employee_checkout_path),
        ),
    ]
