# Generated by Django 5.2.7 on 2025-10-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancerecord_checkin_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Attendance Dashboard',
                'verbose_name_plural': 'Attendance Dashboard',
                'managed': False,
            },
        ),
    ]
