# Generated by Django 5.2.7 on 2025-10-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_dashboardstub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Early Leave', 'Early Leave'), ('Absent', 'Absent'), ('Half Day', 'Half Day'), ('On Leave', 'On Leave'), ('Holiday', 'Holiday'), ('Pending', 'Pending'), ('Off Day', 'Off Day')], max_length=20, null=True),
        ),
    ]
