# Generated by Django 5.2.7 on 2025-10-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
    ]
