# Generated by Django 5.2.7 on 2025-11-01 05:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_employee_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=4)),
                ('present_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=4)),
                ('late_grace_minutes', models.PositiveIntegerField(default=0)),
                ('enable_late_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Early Leave', 'Early Leave'), ('Absent', 'Absent'), ('Half Day', 'Half Day'), ('On Leave', 'On Leave'), ('Holiday', 'Holiday'), ('Pending', 'Pending'), ('Off Day', 'Off Day'), ('Late', 'Late')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='LogicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summer_start', models.DateField(blank=True, null=True)),
                ('summer_end', models.DateField(blank=True, null=True)),
                ('winter_start', models.DateField(blank=True, null=True)),
                ('winter_end', models.DateField(blank=True, null=True)),
                ('active_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for', to='attendance.seasonprofile')),
            ],
            options={
                'verbose_name': 'Edit Logics',
                'verbose_name_plural': 'Edit Logics',
            },
        ),
    ]
