# Generated by Django 5.2.7 on 2025-11-01 05:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_seasonprofile_alter_attendancerecord_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=4)),
                ('present_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=4)),
                ('allowed_late_minutes', models.PositiveIntegerField(default=0, help_text='Allowed minutes after shift start before flagged late')),
                ('enable_late_status', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one shift should be active at a time')),
            ],
            options={
                'ordering': ('-is_active', 'name'),
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='late_duration',
            field=models.DurationField(blank=True, help_text='How long employee was late beyond allowed minutes', null=True),
        ),
        migrations.DeleteModel(
            name='LogicSettings',
        ),
        migrations.DeleteModel(
            name='SeasonProfile',
        ),
    ]
