# Generated by Django 5.2.7 on 2025-11-01 06:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_shift_attendancerecord_late_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summer_start', models.DateField(blank=True, null=True)),
                ('summer_end', models.DateField(blank=True, null=True)),
                ('winter_start', models.DateField(blank=True, null=True)),
                ('winter_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Edit Logics',
                'verbose_name_plural': 'Edit Logics',
            },
        ),
        migrations.CreateModel(
            name='SeasonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=4)),
                ('present_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=4)),
                ('late_grace_minutes', models.PositiveIntegerField(default=0)),
                ('enable_late_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='late_duration',
        ),
        migrations.AddField(
            model_name='logicsettings',
            name='active_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for', to='attendance.seasonprofile'),
        ),
    ]
