# Generated by Django 5.2.7 on 2025-11-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_payrolladjustment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayrollAdjustment',
        ),
    ]
