# Generated by Django 5.2.7 on 2025-11-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_delete_payrolladjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='device_id',
            field=models.CharField(blank=True, help_text='Source device identifier (optional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_encoding',
            field=models.JSONField(blank=True, help_text='128-d face encoding vector for face recognition', null=True),
        ),
    ]
