# Generated by Django 5.2.7 on 2025-11-10 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_attendancerecord_device_id_employee_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Shift used for this attendance day. If empty, falls back to the active shift.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shift'),
        ),
    ]
