# Generated by Django 5.2.7 on 2025-11-10 10:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_attendancerecord_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Daily salary in BDT for bonus/fine calculations', max_digits=10),
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=200)),
                ('date_awarded', models.DateField(auto_now_add=True)),
                ('month', models.DateField(help_text='Month this bonus applies to (YYYY-MM-01)')),
                ('is_automatic', models.BooleanField(default=False, help_text='Auto-generated bonus')),
                ('comments', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
            options={
                'ordering': ('-date_awarded',),
                'unique_together': {('employee', 'month', 'reason')},
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=200)),
                ('date_imposed', models.DateField(auto_now_add=True)),
                ('month', models.DateField(help_text='Month this fine applies to (YYYY-MM-01)')),
                ('is_automatic', models.BooleanField(default=False, help_text='Auto-generated fine')),
                ('comments', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
            options={
                'ordering': ('-date_imposed',),
                'unique_together': {('employee', 'month', 'reason')},
            },
        ),
    ]
