# Generated by Django 5.2.7 on 2025-11-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_employee_daily_salary_bonus_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryReportStub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Salary Report',
                'verbose_name_plural': 'Salary Report',
                'managed': False,
            },
        ),
    ]
