# Generated by Django 5.2.7 on 2025-11-10 10:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_salaryreportstub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='daily_salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly salary in BDT for bonus/fine calculations', max_digits=10),
        ),
    ]
