# Generated by Django 5.2.7 on 2025-11-10 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_remove_employee_daily_salary_employee_monthly_salary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fine',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fine',
            name='employee',
        ),
        migrations.CreateModel(
            name='SalaryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('bonus', 'Bonus'), ('fine', 'Fine')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('month', models.DateField(help_text='Month this adjustment applies to (YYYY-MM-01)')),
                ('is_automatic', models.BooleanField(default=False, help_text='Auto-generated adjustment')),
                ('comments', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
            options={
                'ordering': ('-date_created',),
                'unique_together': {('employee', 'month', 'reason', 'adjustment_type')},
            },
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
        migrations.DeleteModel(
            name='Fine',
        ),
    ]
