# Generated by Django 5.2.7 on 2025-11-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_alter_fine_unique_together_remove_fine_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayManagementStub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Holiday Management',
                'verbose_name_plural': 'Holiday Management',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BulkHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Holiday name (e.g., 'Eid Holiday', 'Project Completion Break')", max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('scope', models.CharField(choices=[('all', 'All Employees'), ('department', 'Department'), ('designation', 'Designation'), ('custom', 'Selected Employees')], default='all', max_length=20)),
                ('department', models.CharField(blank=True, help_text="Required if scope is 'department'", max_length=100, null=True)),
                ('designation', models.CharField(blank=True, help_text="Required if scope is 'designation'", max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether attendance records have been created')),
                ('selected_employees', models.ManyToManyField(blank=True, help_text="Required if scope is 'custom'", to='attendance.employee')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
