# Generated by Django 5.2.7 on 2025-11-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_holidaymanagementstub_bulkholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkholiday',
            name='created_by_name',
            field=models.CharField(blank=True, help_text="Optional display name (e.g., 'Omar Khayam')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bulkholiday',
            name='created_by',
            field=models.CharField(blank=True, help_text='Username who created this holiday', max_length=100, null=True),
        ),
    ]
