# Generated by Django 5.2.7 on 2025-11-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_bulkholiday_created_by_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Holiday name (e.g., 'Independence Day')", max_length=200)),
                ('month', models.PositiveIntegerField(help_text='Month (1-12)')),
                ('day', models.PositiveIntegerField(help_text='Day of month (1-31)')),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='Number of consecutive days')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to auto-generate this holiday')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('month', 'day'),
                'unique_together': {('name', 'month', 'day')},
            },
        ),
    ]
