# Generated by Django 5.2.7 on 2025-11-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_governmentholiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GovernmentHoliday',
        ),
        migrations.RemoveField(
            model_name='bulkholiday',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='bulkholiday',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this holiday is currently active'),
        ),
        migrations.AddField(
            model_name='bulkholiday',
            name='is_government',
            field=models.BooleanField(default=False, help_text='Whether this is a government holiday'),
        ),
    ]
