# Generated by Django 5.2.7 on 2025-11-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_delete_governmentholiday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeManagementStub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Employee Management',
                'verbose_name_plural': 'Employee Management',
                'managed': False,
            },
        ),
    ]
