# Generated by Django 5.2.7 on 2025-11-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_employeemanagementstub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeManagementStub',
        ),
    ]
