# Generated by Django 5.2.7 on 2025-11-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_employee_active_status'),
        ('attendance', '0026_delete_employeemanagementstub'),
    ]

    operations = [
    ]
